export default [
  'arsenal f.c.',
  'olympic games',
  'borussia dortmund',
  'everton f.c.',
  'football league cup',
  'liverpool f.c.',
  'manchester city',
  'association football',
  'fußball-bundesliga',
  '2008–09 in english football',
  'cricket',
  'chelsea f.c.',
  'promotion and relegation',
  'fc bayern munich',
  'summer olympic games',
  'dfb-pokal',
  'france',
  'bt sport',
  'tennis',
  'manchester united',
  '2008 summer olympics',
  'the football association',
  'international olympic committee',
  'sheffield united f.c.',
  'football league championship',
  'the championships, wimbledon',
  'tottenham hotspur f.c.',
  'uefa champions league',
  'golf',
  'liverpool',
  'sky sports',
  'grand slam',
  'bright lights of the cheltenham festival',
  'fa community shield',
  'racing tips',
  'chelmsford city',
  'low-key evening meeting',
  'leeds united a.f.c.',
  'better place',
  'day marlborough',
  'best bets service',
  'own champion tipster marlborough',
  'glorious goodwood',
  'winter olympic games',
  'goodwood racecourse',
  'wolverhampton wanderers f.c.',
  'athens',
  'traditional style',
  'pga tour',
  '1964 summer olympics',
  'manchester',
  'demetrius vikelas',
  'us open',
  'pierre de coubertin',
  'manchester city f.c.',
  'telegraph sport',
  'newcastle united f.c.',
  "nuthin' fancy",
  'boxing',
  'fifa world cup',
  'england national football team',
  'tour de france',
  'sheffield united',
  'bayer 04 leverkusen',
  'australian open',
  'bayern munich',
  'french open',
  'olympic flame',
  'rugby union',
  'cricket world cup',
  'aston villa f.c.',
  'la liga',
  'roger federer',
  'swimming',
  'tokyo paralympic games',
  'friday march',
  'football',
  'fc schalke 04',
  'test cricket',
  'tyson fury',
  'aston villa',
  'real madrid c.f.',
  'chelmsford',
  'munich',
  "giro d'italia",
  'sheffield wednesday f.c.',
  'alex ferguson',
  'horse racing',
  'david beckham',
  'ibf title fight',
  'frankie dettori',
  'west ham united f.c.',
  'debut albums',
  'international cricket council',
  'black-and-white films',
  'jamie carragher',
  'selection',
  'merseyside derby',
  'rafael nadal',
  'serie a',
  'venus williams',
  'england national rugby union team',
  'west ham',
  'players',
  'england cricket team',
  'rugby football union',
  'want',
  'pga championship',
  'serena williams',
  'marcus rashford',
  'gary neville',
  'martina hingis',
  'south africa',
  'american football',
  'guinness premiership',
  'premier league clubs',
  'wednesday june',
  'world boxing council',
  'wembley stadium',
  'eintracht frankfurt',
  'mike tyson',
  'cristiano ronaldo',
  'twenty20',
  'sv werder bremen',
  'premier league title',
  'international rugby board',
  'birmingham city f.c.',
  'swimming pool',
  'fc barcelona',
  'germany national football team',
  'grand national',
  'ascot racecourse',
  'current rights holders sky sports',
  'old trafford',
  'japanese prime minister shinzo abe',
  'wales cricket board',
  'live matches',
  'horse',
  'natural selection',
  'novak djokovic',
  'friday june',
  'player',
  'italy',
  'ascot gold cup',
  'football association',
  'fulham f.c.',
  'green light',
  'otto rehhagel',
  'fc nuremberg',
  'sunderland a.f.c.',
  'man',
  'the open championship',
  'frank lampard',
  'borussia mönchengladbach',
  'champions league',
  'positive results',
  'possession of a 25-point lead',
  'andre agassi',
  'pga european tour',
  'leicester city f.c.',
  'justine henin',
  'crystal palace',
  'skiing',
  'juventus f.c.',
  'rugby league',
  'rugby football',
  'first full matchday',
  'australia',
  'lpga',
  'prize money',
  'professional golf tours',
  'film noir',
  'major league baseball',
  'game',
  'royal ascot',
  'a.c. milan',
  'european qualification',
  'paralympic games',
  'bolton wanderers f.c.',
  'play',
  'rugby world cup',
  'sale sharks',
  "men's major golf championships",
  'aintree racecourse',
  'evander holyfield',
  'ryder cup',
  'jupp heynckes',
  'annika sörenstam',
  'f.c. internazionale milano',
  'eddy merckx',
  'fish',
  'andy murray',
  'tiger woods',
  'thursday march',
  'ancient olympic games',
  'the players',
  'premier league players',
  'official world golf rankings',
  'ocean',
  'fußball-bundesliga',
];
