export default [
  'british airways',
  'cruise ship',
  'ship',
  'airline',
  'hotel',
  'travel',
  'holland america line',
  'royal navy',
  'tourism',
  'cruise line',
  'london gatwick airport',
  'cruise ships',
  'london heathrow airport',
  'easyjet',
  'virgin atlantic airways',
  'spain',
  'aircraft',
  'broadsheet',
  'pacific',
  'ocean liner',
  'airport',
  'cruise',
  'ryanair',
  'southwest airlines',
  'crew members',
  "world's busiest airports by passenger traffic",
  'low-cost carrier',
  'city guides',
  'princess cruises',
  'telegraph travel',
  'passenger ship',
  'cruise lines',
  'canary islands',
  'travel agency',
  '1975',
  'london luton airport',
  'hotels',
  'carnival cruise lines',
  'us airways',
  'air france',
  'south america',
  'holiday',
  'americas',
  'travel restrictions',
  '1978',
  'beach',
  'flight',
  'mediterranean sea',
  '1967',
  'baa limited',
  '1980',
  'united airlines',
  '1977',
  'navy',
  'world tourism organization',
  'avianca',
  'best hotels',
  'pakistan international airlines',
  'united states navy',
  'travel industry',
  'december',
  'qantas',
  'north america',
  'air traffic control',
  'best things',
  'cabin crew',
  'fort lauderdale, florida',
  'greece',
  'busiest airports in the united kingdom by total passenger traffic',
  'passenger',
  'aircraft carrier',
  'air travel',
  '1983',
  'caribbean',
  '1982',
  'the love boat',
  'france',
  'meyer werft',
  'australia',
  'jinnah international airport',
  'wizz air',
  '2006',
  'virgin atlantic',
  'italy',
  'insurance',
  'public transport',
  'answer',
  'transport',
  'frigate',
  'south africa',
  'aer lingus',
  '1966',
  'airlines',
  'social network service',
  'telegraph expert rating',
  'island',
  'london stansted airport',
  'boutique hotel',
  'dec',
  'money',
  'union flag',
  'knowledgeable guides   see europe',
  'boeing 747-400',
  'question',
  'delta air lines',
  'package holiday',
  'royal air force',
  'boeing 737',
  'foreign office',
  'boeing 747',
  '1989',
  '1979',
  'coast',
  'rms titanic',
  'english channel',
  'customer',
  'new year',
  'atlantic ocean',
  'civil aviation authority',
  'walt disney world resort',
  'balearic islands',
  'karachi',
  'world war i',
  'customer service',
  'new south wales',
  'white star line',
  'cargo ship',
  "city's best museums",
  'main attractions',
  'french navy',
  'ocean',
  'air bridges',
  'destroyer',
  'new york',
  'cargo',
  '1944',
  'rooms',
  'bmi',
  'norway',
  'tour operator',
  'boeing 787',
  'airbus a320 family',
  'nov',
  'train',
  'resort',
  '1961',
  '1960',
  'united arab emirates',
  'ferry',
  'international air transport association',
  'modern slavery',
  'latin america',
  'africa',
  'insider guide',
  'user',
  'face',
  'want',
  'rail transport',
  'login',
  'federal aviation administration',
  'airline hub',
  'passport',
  'lahore',
  'richard branson',
  'passenger numbers',
  'ottoman empire',
  'paris',
  'motel',
  'indigenous peoples of the americas',
  'oneworld',
  'costa rica',
  'locomotive',
  'pakistan',
  'argentina',
  'walt disney',
  'catalan language',
  'days of the year',
  'air safety',
  'royal caribbean cruises ltd.',
  'package travel regulations',
  'indian ocean',
  'american airlines',
  'titanic',
  'inn',
  'sun',
  'cornwall',
  'british nationals',
  'the guardian',
  'heathrow airport',
  'traveler',
  'home secretary priti patel',
  'travel firms',
  'travel companies',
  'british army',
  'law',
  '2007',
  '1971',
  'commonwealth office',
  '1972',
  'boat',
];
