name: Build, Test and maybe Publish
on: [push, pull_request]

jobs:
  
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build
        run: npm install
      - name: Test
        run: npm test
  
  publish:
    name: Publish to NPM
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@4f4bf159e299f65d21cd1cbd96fc5d53228036df
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^release: (\\S+)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
